# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy remaining source code
COPY . .

# Build the project and ensure the entrypoint has execute permissions
RUN npm run build

# Expose any ports if necessary (not specified in MCP, so skipped)

CMD ["node", "build/index.js"]
